account balances
figment-networks/indexer-manager pull request #20
Opened 2021-02-25 18:39 UTC by eesmerdag

2021-03-01 17:05 UTC, pacmessica requested changes
looks pretty good! thanks for the fixes in the rewards call :)

Update the README to include the new endpoint

2021-03-01 17:05 UTC, pacmessica commented on structs/structs.go
> +type BalanceAmount struct {
This is missing `Currency` and `Exp` which are important. So rather than create a new type, just use `TransactionAmount` struct in `BalanceSummary`.

2021-03-02 13:24 UTC, patiee commented on structs/requests.go
> +	Balances []TransactionAmount `json:"balances"`
```suggestion
	Balances []TransactionAmount `json:"balances,omitempty"`
```

2021-03-02 13:25 UTC, patiee approved these changes

2021-03-03 10:42 UTC, pacmessica requested changes
works! found a couple minor things while testing

2021-03-03 10:42 UTC, pacmessica commented on manager/transport/http/http.go
> +	address := req.URL.Query().Get("address")
use "account" for query string name. We use that for /rewards endpoint already, so it's nice to be consistent

2021-03-03 10:42 UTC, pacmessica commented on manager/client/client.go
> +			Start:  row.startHeight,
we don't need start/end fields. For rewards we calculated rewards for an entire day start->end. For balances, we are only getting a 'snapshot' of the balance every 24h. So 'Height' makes more sense here.

2021-03-03 10:42 UTC, pacmessica commented on manager/client/client.go
> +			Start:  row.startHeight,
so you can also simplify the for loop on line 659 ( track height instead of startHeight/endheight for example)

2021-03-03 14:06 UTC, eesmerdag commented on manager/client/client.go
> +					return balances, fmt.Errorf("error decoding reward: %w", err)
👍

2021-03-03 14:07 UTC, eesmerdag commented on structs/structs.go
> +type BalanceAmount struct {
👍

2021-03-03 14:25 UTC, eesmerdag commented on manager/transport/http/http.go
> +	address := req.URL.Query().Get("address")
👍

2021-03-03 17:29 UTC, pacmessica approved these changes
small fix, then you can merge.

2021-03-03 17:29 UTC, pacmessica commented on README.md
> +| `numeric` | `number` | `big.Tnt` | an integer representation of `amount` without decimal places, such that `amount = numeric * 10^(-exp)` |
big.Int not Tnt. fix for rewards description too

include exp in description because maybe it exists for another network

2021-03-03 17:38 UTC, merged