tracking chain head
figment-networks/indexer-manager pull request #56
Opened 2021-09-14 15:57 UTC by eesmerdag

2021-09-15 11:41 UTC, lukanus commented on manager/client/client.go
> +	lastIndexedBlock, err := hc.storeEng.GetLatestBlock(ctx, blockWithMeta)
Taking record from the database first will make it better, also this seemed to always fail for the new tasks. Is this done like that in purpose?

2021-09-15 12:51 UTC, eesmerdag commented on manager/client/client.go
> +	lastIndexedBlock, err := hc.storeEng.GetLatestBlock(ctx, blockWithMeta)
yes sir you are right, I will change the code to take first data from chain and then from db for case when worker is offline.

But I did not get this "this seemed to always fail for the new tasks." you mean when the case there is no row in the db?

2021-09-15 14:31 UTC, eesmerdag commented on manager/client/client.go
> +	lastIndexedBlock, err := hc.storeEng.GetLatestBlock(ctx, blockWithMeta)
yes sir, manager is supposed to fetch the data for new chain/worker immediately. so in that short time range, I will change error message 🤝

2021-09-16 14:48 UTC, pacmessica requested changes

2021-09-16 14:48 UTC, pacmessica commented on structs/requests.go
> +	LatestIndexedBlockHeight uint64    `json:"latest_indexed_block_height"`
block time isn't necessary - then you don't need to create new calls in all the workers. There should be existing calls in worker to fetch latest block or block height or something. Use those and remove this field

2021-09-16 14:48 UTC, pacmessica commented on structs/requests.go
> +	BehindChain              bool      `json:"behind_chain"`
Could you return Lag instead of BehindChain? ie where Lag = LatestBlockHeight - LatestIndexedBlockHeight

```
	// Lag is how many blocks the indexer is behind the current head of the chain
	Lag int64 `json:"indexing_lag,omitempty"`
```

2021-09-16 14:48 UTC, pacmessica commented on manager/transport/http/http.go
> +	mux.HandleFunc("/get_chain_head", c.GetChainHead)
`/indexing_status` and `c.IndexingStatus` is more descriptive. "get chain head" sounds like you're fetching the latest block from the chain and returning the whole thing.

2021-09-16 16:14 UTC, eesmerdag commented on structs/requests.go
> +	BehindChain              bool      `json:"behind_chain"`
I think this should be
 **Lag = now() - LatestIndexedBlockTime**

2021-09-16 16:58 UTC, pacmessica commented on structs/requests.go
> +	BehindChain              bool      `json:"behind_chain"`
Lag = latestBlock.Height - lastindexedblcok.height

That's the convention we use in other indexers

2021-09-16 17:00 UTC, pacmessica commented on structs/requests.go
> +	LatestIndexedBlockHeight uint64    `json:"latest_indexed_block_height"`
It doesn't look like you did this.

fetch latest block from chain still because fetching height is still important info and It's good to see what the current head is at when debugging.Also need that to calculate lag.  Include  latestBlock.Height in response.

2021-09-16 17:04 UTC, pacmessica commented on structs/requests.go
> +	BehindChain              bool      `json:"behind_chain"`
I dont know how slack channel alerts work. Did you find out? The time calculation you're doing here for lag is done somewhere else for the slack channel alert - I know in the past we've increased the threshold from 1 hour to 4 hours when polkadot was super slow without redeploying the repo

2021-09-22 02:26 UTC, pacmessica approved these changes
some minor changes to simplify code, otherwise lgtm

2021-09-22 02:26 UTC, pacmessica commented on manager/client/client.go
> +	if len(reqs) > 0 {
unnecessary check, this is always true

2021-09-22 02:26 UTC, pacmessica commented on manager/client/client.go
> +	}
There's only one request, so you don't need a WaitForAllData loop. There will only be one response on respAwait.Resp, so you can simplify this (don't need to track finals, or use a decoder buffer, etc):

something like this should work fine
```suggestion
	for {
		select {
		case <-ctx.Done():
			return info, errors.New("request timed out")
		case response, ok := <-respAwait.Resp:
			if !ok {
				return info, fmt.Errorf("resp channel closed")
			}
			hc.logger.Debug("[Client] Get chain head received data:", zap.Any("type", response.Type), zap.Any("response", response))

			if response.Error.Msg != "" {
				return info, fmt.Errorf("error getting response: %s", response.Error.Msg)
			}

			if response.Type != "ChainHeadBlock" {
			    return info, fmt.Errorf("error getting ChainHeadBlock: wrong response type: %s", response.Type)
			}
			
			if err = json.Unmarshal(response.Payload, lastBlockOfChain); err != nil {
			    return info,  fmt.Errorf("error unmarshalling latest block: %s", response.Error.Msg)
			}
		}
	}
```

2021-09-22 12:15 UTC, eesmerdag commented on manager/client/client.go
> +	if len(reqs) > 0 {
👍

2021-09-22 13:44 UTC, eesmerdag commented on manager/client/client.go
> +	}
👍

2021-09-22 13:56 UTC, merged